apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-nfs
spec:
  selector:
    matchLabels:
      app: mongodb-nfs # has to match .spec.template.metadata.labels
  serviceName: "mongodb-nfs"
  template:
    metadata:
      labels:
        app: mongodb-nfs # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 1Gi